name: lido-token-seller

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.7.3
    exclude:
      - package.json    # Ignore package.json files.
      - mocks/**/*      # Ignore all files in the 'mocks' directory

solidity: 
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.7.3"

plugins:
  - name: solidity
    version: 0.4.1
  - name: vyper
    version: 0.4.0
  - name: hardhat
    version: 0.4.2
  - name: infura
    version: 0.4.0

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura